language: cpp
sudo: required
dist: trusty
before_install:
  - sudo apt-get update -q
  - sudo apt-get install g++ -y
  - export CXX="g++"
  - git clone --branch=release --depth=1 https://github.com/jpcre2/pcre2
  - cd pcre2
  - autoreconf -v -i
  - ./configure && make
  - sudo make install
  - cd -
script: ./autogen.sh; ./configure && make && make check
